#!/bin/bash
#GOOD MORNING PROFESSOR
#THIS IS MY SYSTEM REPORT 


user_name=$USER
# I have generated the system report firstly
echo "
System Report generated by $user_name, $(date)"



#System information description 
echo -e "\nSystem Information"
echo "---------------------"
#the hostname is provided
echo "Hostname: $(hostname)"
#Operating system is  described
echo "OS: $(source /etc/os-release && echo $PRETTY_NAME)"
#time spent on the system  
echo "Uptime: $(uptime -p)"


#for hardware info I used lscpu,lsblk, lshw and lspci  commands according to the info needed
#model brief info
Cpu_Model=$(lscpu | grep 'Model name' | awk -F': ' '{print $2}')
#cpu current speed and max speed is shown
Current_Speed=$(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /size:/{print $2; exit}') 
Max_Speed=$(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /capacity:/{print $2; exit}')
#random memory access size 
Cpu_RAM=$(sudo lshw -short -C memory | grep -i 'system memory' | awk '{print $3}')
# disks in computer descrption
Cpu_Disks=$(lsblk --output NAME,SIZE,TYPE,MOUNTPOINT,LABEL --exclude 7 | awk '!/loop/ {printf "%-8s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3, $4, $5, $6}')
#the video card name and some other info
Video_card=$(lspci -nnk | grep -i 'VGA' | awk -F': ' '{print $2}' | uniq)



echo -e  "\nHardware Information"
echo "---------------------"

cat <<EOF
cpu: $Cpu_Model
Speed: $Current_Speed
MaxSpeed: $Max_Speed
Ram: $Cpu_RAM

Disk(s): $Cpu_Disks

Video: $Video_card

EOF


# Network Information description
echo -e "\nNetwork Information"
echo "---------------------"
#fully qualified domain name below 
echo -e "\nFQDN: $(hostname -f)"
#the IP address of the hostname 
echo "Host Address: $(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')"
# the address if the gateway 
echo "Gateway IP: $(ip r | awk '/default/ {print $3}')"
#detail of DNS server  with help of grep 
echo "DNS Server: $(grep -E '^nameserver' /etc/resolv.conf | awk '{print $2}')"



#interface information showing network card model brief info and representing IP address  in CIDR format
info_network=$(cat <<EOF

InterfaceName: $(sudo lshw -class network | grep -E 'description|product|vendor|physical id|logical name' | awk -F ':' '{print $1 ": " $2}')

IP Address: $(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')
EOF
)

echo "
$info_network"

# System Status detail
echo -e "\nSystem Status"
echo "---------------------"
#Currently logged user
echo -e "\nUsers Logged In: $(who | awk '{print $1}' | sort | uniq | paste -s -d ',')"
#indicating free disk space
echo -e "\nDisk Space: $(df -h)"
#the count of the process or its status 
echo -e "\nProcess Count: $(ps -e | wc -l)"
#average load on  CPU or processor with uptime usage
echo "Load Averages: $(uptime | awk -F'[a-z]:' '{print $2}')"
#assigning space to different programs using print 
echo -e "\nMemory Allocation:\n$(free -h | awk '/^Mem:/ {print "Type\tTotal\tAvailable"; print $1 "\t" $2 "\t" $7}')"
#brief info of listening ports  with different commands 
echo -e "\nListening Network Ports:\n$(ss -tuln | awk 'BEGIN {print "State\tRecv-Q\tSend-Q\tLocal Address:Port\tPeer Address:Port"} /LISTEN/ {print>
#uncomplicated firewalls  manages firewalls 
echo -e "\nUFW Rules: $(sudo ufw status numbered | grep -v 'Status: active')"





#END OF MY SCRIPT 
#HOPE YOU LIKED MY SCRIPT 
